### ISSUE TITLE
[Feature request] Allow more sources of data

### ISSUE THREAD

**Issue by kubark42** [cdens/PySpectrogram#2]
This is a great program! I would love to use this with a datastream which is coming in over the serial port, instead of the microphone. 

Python isn't my best language, but if there were a well-delineated file where it was clear how the data got into the core of the program, I feel like we could probably extend that to any arbitrary data source.

I can modify my data stream to have any data format to fit PySpectrogram (although because it's serial and thus bandwidth constrained simpler formats will be better).

**Comment by cdens** [comment]
The code you're looking for is in lines 54-70 of AudioProcessor.py

That function uses the PyAudio library to identify all potential audio sources with at least one input channel of audio data. I have to look more closely at the PyAudio documentation but I think if your computer recognizes the serial input as an audio source then it should be a selectable source in the drop-down menu. 

If not, adding support would require modifying that function and other code in the same file to select the audio source, specifically integrating another library that can identify and read data from your serial port source.

**Comment by kubark42** [comment]
Thanks, I'll give it a look!
